### PR TITLE
add first saltcheck tests

### PR DESCRIPTION
**Pull request by mchugh19**
As mentioned in 
https://github.com/saltstack-formulas/template-formula/issues/87

First draft at adding saltcheck tests. Uses functionality from saltcheck module from Neon as well as https://github.com/saltstack/salt/pull/52441 patch to cron module. Without the cron module patch functionality, the service and install tests function, but the return from `cron.ls` isn't very parsible. 

Given a pillar:
```
cron:
  enabled: True      # Default
  tasks:
    task1:
      type: present  # Default
      name: echo test > /tmp/test
      user: root
      minute: 0
      hour: 0
      daymonth: 7
      month: 1
      dayweek: 6
      comment: comment1
    task2:
      type: absent
      name: echo task2 > /tmp/test2
      user: root
      minute: random
      hour: 1
```

With an existing crontab of
```
# crontab -l
# Lines below here are managed by Salt, do not edit
# comment1 SALT_CRON_IDENTIFIER:task1
0 0 8 1 6 echo test > /tmp/test

# salt-call cron.ls root
local:
    ----------
    crons:
        |_
          ----------
          cmd:
              echo test > /tmp/test
          comment:
              comment1
          commented:
              False
          daymonth:
              8
          dayweek:
              6
          hour:
              0
          identifier:
              task1
          minute:
              0
          month:
              1
    env:
    pre:
    special:
```
NOTE: I've manually edited the cron entry's "daymonth" from 7 to 8

```
# salt-call saltcheck.run_state_tests cron check_all=True
[WARNING ] The 'environment' minion config option has been renamed to 'saltenv'. Using base as the 'saltenv' config value.
local:
    |_
      ----------
      cron:
          ----------
          verify_cron.install:
              ----------
              duration:
                  1.5572
              status:
                  Pass
          validate_cron.task1_hour:
              ----------
              duration:
                  0.0769
              status:
                  Pass
          validate_cron.task2_absent:
              ----------
              duration:
                  0.0464
              status:
                  Pass
          validate_cron.task1_month:
              ----------
              duration:
                  0.0439
              status:
                  Pass
          validate_cron.task1_daymonth:
              ----------
              duration:
                  0.0526
              status:
                  Fail: 7 is not equal to 8
          validate_cron.task1_minute:
              ----------
              duration:
                  0.0532
              status:
                  Pass
          validate_cron.task1_comment:
              ----------
              duration:
                  0.0487
              status:
                  Pass
          validate_cron.task1_dayweek:
              ----------
              duration:
                  0.0527
              status:
                  Pass
          validate_cron.task1_exists:
              ----------
              duration:
                  0.0467
              status:
                  Pass
          test_cron_service_enabled:
              ----------
              duration:
                  1.4451
              status:
                  Pass
          test_cron_service_running:
              ----------
              duration:
                  0.4851
              status:
                  Pass
    |_
      ----------
      TEST RESULTS:
          ----------
          Execution Time:
              3.9085
          Failed:
              1
          Missing Tests:
              0
          Passed:
              10
          Skipped:
              0
```

As shown above, all tst files in the saltcheck-tests directory can be run with:
`salt-call saltcheck.run_state_tests cron check_all=True`

Or individual test files can be run:
`# salt-call saltcheck.run_state_tests cron.install`

If this is run on a minion which has the cron module defined in top.sls as part of highstate, then tests can be run for all highstate associated states with:
`# salt-call saltcheck.run_highstate_tests`

Also, like all salt commands, output can be displayed as json for better parsing:
```
# salt-call saltcheck.run_state_tests cron check_all=True --output json
[WARNING ] The 'environment' minion config option has been renamed to 'saltenv'. Using base as the 'saltenv' config value.
{
    "local": [
        {
            "cron": {
                "validate_cron.task1_hour": {
                    "status": "Pass",
                    "duration": 0.0734
                },
                "test_cron_service_enabled": {
                    "status": "Pass",
                    "duration": 1.4594
                },
                "validate_cron.task2_absent": {
                    "status": "Pass",
                    "duration": 0.0487
                },
                "validate_cron.task1_comment": {
                    "status": "Pass",
                    "duration": 0.049
                },
                "test_cron_service_running": {
                    "status": "Pass",
                    "duration": 0.4853
                },
                "validate_cron.task1_month": {
                    "status": "Pass",
                    "duration": 0.0424
                },
                "validate_cron.task1_daymonth": {
                    "status": "Fail: 7 is not equal to 8",
                    "duration": 0.0485
                },
                "validate_cron.task1_minute": {
                    "status": "Pass",
                    "duration": 0.0488
                },
                "verify_cron.install": {
                    "status": "Pass",
                    "duration": 1.5029
                },
                "validate_cron.task1_dayweek": {
                    "status": "Pass",
                    "duration": 0.0484
                },
                "validate_cron.task1_exists": {
                    "status": "Pass",
                    "duration": 0.0508
                }
            }
        },
        {
            "TEST RESULTS": {
                "Failed": 1,
                "Missing Tests": 0,
                "Skipped": 0,
                "Passed": 10,
                "Execution Time": 3.8576
            }
        }
    ]
}
```

### CODE REVIEW

**Comment by mchugh19** [comment]
By defining saltcheck tests in upstream formulas, it can be used as part of the forumula's CI pipeline, but also gives users of the formula the ability to validate deployed environments as well. So rather than needing to run a possibly heavyweight `state.sls cron test=True` and parse output for changes, you could also run saltcheck and see if there's a config gap.

**Comment by myii** [comment]
@mchugh19 Following on from the updated discussions in https://github.com/saltstack-formulas/template-formula/pull/88, I've tested the various modifications required to get this all working as well.  It would be even nicer if we could get relative imports working.

**Comment by mchugh19** [comment]
> It would be even nicer if we could get relative imports working.
If I'm following correctly, I think the issue with relative imports is needing map files or other includes copied over to the minion in order to fully render. This should be properly fixed in https://github.com/saltstack/salt/pull/53068 which should be in neon. 

@myii are you able to test with this version to see if it fixes your issues? https://raw.githubusercontent.com/saltstack/salt/2088199f0714fc0bff416ba11497371cdb993a3b/salt/modules/saltcheck.py

**Comment by myii** [comment]
@mchugh19 Since we're running `develop`, the current tests have been done with:

* https://github.com/saltstack/salt/blob/develop/salt/modules/saltcheck.py

I'll test this version and let you know how it gets on.

**Comment by mchugh19** [comment]
Unfortunately, I think develop does not yet include the PR mentioned which reworks how files are copied and render dependencies pulled in. Worst case, you should be able to wait a couple of weeks (fingers crossed!) for the backlog of PRs to be merged in.

**Comment by myii** [comment]
@mchugh19 Not a problem, worst case I can pull in the file during the Travis run.  I've already been testing that when making modifications to it, such as dealing with the missing error code.  I'm testing it now, so I should have a response for you fairly soon.

**Comment by myii** [comment]
@mchugh19 OK, making progress but I'm at the stage of figuring out how to run the tests.  This was working fine up to now:

```bash
$ sudo salt-call --config-dir=/tmp/kitchen/etc/salt saltcheck.run_state_tests cron check_all=True
```

That still works with the old file but not the new.  It reports as `Missing Tests`.

**Comment by myii** [comment]
Right, so it's looking in different locations to what I expected:

```sls
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests  
looking in %s to cache tests salt://cron/service/running/saltcheck-tests
looking in %s to cache tests salt://cron/service/saltcheck-tests
```

* It's not picking up `salt://cron/config/...`, either.
* Let alone `salt://cron/...`.

The original location (with the file from `develop`) is:

```sls
searching path: %s /tmp/kitchen/var/cache/salt/minion/files/base  
Found test: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/saltcheck-tests/config.tst
Found test: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/saltcheck-tests/service.tst
Found test: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/saltcheck-tests/install.tst
```

**Comment by mchugh19** [comment]
Interesting, that should work! I'll take a look this week.

**Comment by myii** [comment]
@mchugh19 So I've adjusted the location of the tests for the time being, noting that:

> The ``saltcheck-tests`` folder can be customized using the ``saltcheck_test_location`` minion configuration setting.

The important thing is that it appears to be working with relative imports in `map.jinja`.  That's a great result.  It still _isn't_ sending through an appropriate exit code, as I've mentioned here:

* https://github.com/myii/salt/commit/e7a48c0427c1780696f1be2f9d6192b226bc6fde

I'm going to try to put this all together now to form a final solution to be implemented here.  Thanks for linking me to the updated file!  That'll make a significant difference.

**Comment by myii** [comment]
OK, there's a bug present in determining the path.

```bash
$ sudo salt-call --config-dir=/tmp/kitchen/etc/salt config.get saltcheck_test_location
local:
    tests/integration/saltcheck
$ sudo salt-call --config-dir=/tmp/kitchen/etc/salt saltcheck.run_state_tests cron check_all=True
looking in %s to cache tests salt://cron/package/install/tests/integration/saltcheck
looking in %s to cache tests salt://cron/package/tests/integration/saltcheck
looking in %s to cache tests salt://cron/service/running/tests/integration/saltcheck
looking in %s to cache tests salt://cron/service/tests/integration/saltcheck
```

My expectation for that configuration would be: `salt://cron/tests/integration/saltcheck`.

**Comment by mchugh19** [comment]
> OK, there's a ~bug~ surprising method present in determining the path.

@myii  Can you try this untested version? https://gist.github.com/mchugh19/340874466f0799348b1c0be1ee022490

It *should* better handle your salt://state_root/saltcheck_test_location use-case.

**Comment by myii** [comment]
@mchugh19 OK, I will do.  I've got it working with the current version but it's only running the tests for `cron.install`.

* https://travis-ci.org/myii/cron-formula/builds/597864786

Called using:

```bash
sudo salt-call --config-dir=/tmp/kitchen/etc/salt saltcheck.run_state_tests cron check_all=True
```

**Comment by myii** [comment]
@mchugh19 Following on from the previous comment, it looks like it stops searching for paths when it finds the first one, that's why the rest of the tests aren't found.

https://travis-ci.org/myii/cron-formula/jobs/597872502#L2426-L2427

```sls
       looking in %s to cache tests salt://cron/package/install/saltcheck-tests
       looking in %s to cache tests salt://cron/package/saltcheck-tests
```

**Comment by mchugh19** [comment]
> it stops searching for paths when it finds the first one

That was the intent that you would have a saltcheck-tests directory at the root of your state. What file structure are you using?

**Comment by myii** [comment]
@mchugh19 That comment was referring to the version from `neon` that you linked to earlier.  For that, I put a `saltcheck-tests` directory under each sub-directory, with the tests split accordingly, i.e.

```bash
salt://cron/config/saltcheck-tests
salt://cron/package/saltcheck-tests
salt://cron/service/saltcheck-tests
```

I'm now in the process of checking the one from the GitHub gist.

**Comment by myii** [comment]
@mchugh19 Looking promising.

https://travis-ci.org/myii/cron-formula/jobs/597878982#L2230-L2232

```salt
       looking in %s to cache tests salt://cron/package/install/saltcheck-tests
       looking in %s to cache tests salt://cron/package/saltcheck-tests
       looking in %s to cache tests salt://cron/saltcheck-tests```
```

Still not running the `cron.config` tests.  I suspect this is because the test pillar isn't coming through properly, which was working with the original version of `saltcheck.py`.  I'm going to have to do some local testing to confirm that.

**Comment by myii** [comment]
@mchugh19 OK, finally figured it out.  These new versions are still not working with the `tpldata` values.

```sls
looking in %s to cache tests salt://cron/saltcheck-tests
[ERROR   ] tplroot
.
[ERROR   ] tplfile

[ERROR   ] tpldir
.
[ERROR   ] tpldot

[ERROR   ] slspath

```

* Compare this with the table shown in https://github.com/saltstack-formulas/template-formula/pull/88#issuecomment-541635097.

This means the pillar doesn't get merged, which is why the `config` tests aren't being loaded:

https://github.com/saltstack-formulas/cron-formula/pull/4/files#diff-7df4435e3dd75cc6c438b17227fc6955R3

```sls
{%- if 'tasks' in cron_settings %}
```

* `tasks` are merged in from the pillar.

So I'll stick with a local `map.jinja` with non-relative imports, like I had it working earlier.  I'll figure out the version of `saltcheck.py` to use as well.  When I have it ready, I'll let you know.  Thanks for the feedback.

**Comment by myii** [comment]
@mchugh19 For your information, things are looking a bit ominous for Saltcheck:

* https://github.com/saltstack-formulas/template-formula/pull/88#issuecomment-542745280

This PR is the last, great hope!  How would you like to proceed?  Shall I add my commits on top or shall I open this in a separate PR?

**Comment by mchugh19** [comment]
@mii happy to have your comments on top. I'll add you to the fork momentarily.

As for use of saltcheck within the saltstack-formulas project, I listed off what I consider to be the most important reasons for why using saltcheck makes sense. Looking over the responses, I don't think those points were all addressed or were addressed only partially: one (valid) counterpoint was that some of the listed features would only be available on neon or newer and thus tie tests to a specific version. While true, this was mentioned while the team was in discussion about needing to move to a newer version of inspec to use new functionality, showing this is not a unique case to saltcheck. 

That said, the most important criteria is the team's ability to support and maintain the whole system. If it's just familiarity or emotional preference which makes the decision, that's still pretty valid. The team will need to decide what they can or choose to support and maintain. 


I'd argue that even if inspec is used as the primary CI tool, it makes sense to host saltcheck tests for formulas to allow end-users access to validations too. But like I said, that's a decision for the support team to make.

**Comment by myii** [comment]
@mchugh19 I was able to do it without the invite, thanks.  Just wanted to get your permission to amend this PR, using "maintainer mode"!  Please have a look at the changes to see what you think of them.

**Comment by mchugh19** [comment]
That all looks good to me. Nicely done!

**Comment by myii** [comment]
You're welcome.  Let me see if I can convince the others to let this be merged!  Thanks for persisting with this.

**Comment by myii** [comment]
@mchugh19 OK, I've pushed a few more commits here, after a discussion with @javierbertoli about some concerns.  It follows on from the same points made by @daks previously, starting in https://github.com/saltstack-formulas/template-formula/pull/88.  @aboe76 You may find this interesting, also.

One of the main concerns is that `saltcheck` will end up being blind-sided by sharing the same codebase as the Salt modules, states and formulas.  One issue is the shared use of `map.jinja` -- if there's a problem there, `saltcheck` will fail to catch the problem since it is broken in exactly the same way.  So we're going to approach this more like we do with InSpec -- separating the execution between the code and the tests as much as possible.  So no shared `map.jinja`; in fact, no `map.jinja` at all.

One thing I've been able to do (and appreciate) is the near 1:1 relationship between the code and the tests.  You can literally work through the `.sls` in blocks from top to bottom, writing tests for each section as you go along.  It feels like you could achieve maximum test coverage with this method.  To help explain that, I'm going to diff each section of the `.sls` and `.tst`, to appreciate how similar they are.  It would have been easier to do this side-by-side but GitHub isn't the easiest place to do this.  So I'm going to allow myself a little leeway, so that lines that are effectively the same don't drown things out.  The `-` side is the `.sls` and the `+` side is the `.tst`.

#### [1] Getting the data

```diff
-{%- from tplroot ~ "/map.jinja" import cron with context %}
+{%- set cron = salt['pillar.get']('cron', {}) %}
```

* Only using `pillar.get` to pull in the test pillar at `test/salt/pillar/cron.sls`.
* Since this is a Salt module, I figured that this is the middle ground.
* I've also tested with literal values and it works fine but it's too much effort to maintain, in my opinion, with nothing being gained:

```sls
{%- set cron = {
        'enabled': true,
        'tasks': {
            'task1': {
                'type': 'present',
                'name': 'echo test > /tmp/test',
                'user': 'root',
                'minute': 0,
                'hour': 0,
                'daymonth': 7,
                'month': 1,
                'dayweek': 6,
                'comment': 'comment1',
                'commented': false,
            },
            'task2': {
                'type': 'absent',
                'name': 'echo task2 > /tmp/test2',
                'user': 'root',
                'minute': 'random',
                'hour': 1,
            },
            'task3': {
                'type': 'present',
                'name': 'echo task3 > /tmp/test3',
                'user': 'root',
                'special': '@hourly',
                'comment': 'comment3',
            },
            'task4': {
                'type': 'present',
                'name': 'echo task4 > /tmp/test4',
                'user': 'root',
                'minute': '*/5',
                'hour': '*',
                'comment': 'comment4',
            },
            'task5': {
                'type': 'present',
                'name': 'echo task5 > /tmp/test5',
                'user': 'root',
                'minute': 'random',
                'hour': 1,
                'commented': true,
            },
        },
    } %}
```

#### [2] Loop/variables

```diff
 {%- for task, task_options in cron.get('tasks', {}).items() %}
 {%-   set cron_type = task_options.type|d('present') %}
```

* Identical on both sides.

#### [3] Cron entry `present`/`absent`

```diff
-cron.{{ task }}:
-  cron.{{ cron_type }}:
-    - name: {{ task_options.name }}
-    - user: {{ task_options.user|d('root') }}
-    - identifier: '{{ task }}'
+validate_cron.{{ task }}_{{ cron_type }}:
+  module_and_function: cron.get_entry
+  args:
+    - {{ task_options.user|d('root') }}
+    - {{ task }}
+  {%- if cron_type == 'absent' %}
+  assertion: assertFalse
+  {%- else %}
+  assertion: assertEqual
+  assertion_section: identifier
+  expected-return: {{ task }}
+  {%- endif %}
```

* Identical expressions used on both sides.

#### [4] Continue the rest of `.sls`/`.tst` for `present` only

```diff
 {%- if cron_type == 'present' %}
```

* Identical on both sides.

#### [5] Test for `commented`

```diff
-    - commented: {{ task_options.commented|d(False) }}
+validate_cron.{{ task }}_commented:
+  module_and_function: cron.get_entry
+  args:
+    - {{ task_options.user|d('root') }}
+    - {{ task }}
+  assertion: {{ 'assertTrue' if task_options.commented|d(False) else 'assertFalse' }}
+  assertion_section: commented
```

* Using the same expression on both sides.

#### [6] Inner loop and conditional

```diff
+{#-   Note: `special` is `spec` in the module #}
- {%-   for section in ['minute', 'hour', 'daymonth', 'month', 'dayweek', 'comment', 'special'] %}
+ {%-   for section in ['minute', 'hour', 'daymonth', 'month', 'dayweek', 'comment', 'spec'] %}
 {%-     if section in task_options %}
```

* Essentially identical again on both sides.

#### [7] Testing every cron setting

```diff
-    - {{ section }}: '{{ task_options[section] }}'
+{%-       set expected = task_options[section] %}
+validate_cron.{{ task }}_{{ section }}:
+  module_and_function: cron.get_entry
+  args:
+    - {{ task_options.user|d('root') }}
+    - {{ task }}
+  assertion: {{ 'assertLessEqual' if expected == 'random' else 'assertEqual' }}
+  assertion_section: {{ section }}
+  expected-return: '{{ 0 if expected == 'random' else expected }}'
```

* Made slightly more complicated by the way `random` works but even then, an easy translation.
* This little block already provides almost 20 tests, effectively every item from the pillar data is tested. 

#### [8] Closing all of the loops and conditionals

```diff
    {%-     endif %}
    {%-   endfor %}
    {%- endif %}

{%- endfor %}
```

* Identical on both sides.

---

Compare the two files side-by-side in an editor, to appreciate the similarities I'm tried to highlight above.

In terms of the results:

* https://travis-ci.com/saltstack-formulas/cron-formula/jobs/247009755#L2091-L2103

```sls
             ----------
             TEST RESULTS:
          ----------
          Execution Time:
              3.7203
          Failed:
              0
          Missing Tests:
              0
          Passed:
              25
          Skipped:
              0
```

* Scroll up from there to see details of all of the tests that were run.

**Comment by mchugh19** [comment]
Agreed @myii, I also appreciate how being able to leverage salt modules for testing gives deep introspection for validation and test coverage (I originally patched saltcheck to suit our needs when deploying large hadoop clusters in multi cloud environments and needing to ensure that data stores, xml hadoop configs, versioned jar deployments, databases, and seeded data were all in the expected state). As you say, it's also powerful in by leveraging jinja and the salt renderer, you keep a very similar syntax, and can access map.jinja or pillars as desired. 

I think there are a few different ways you could treat saltcheck testing. For formula CI processes, you could test

1. The result of the map.jinja data inheritance process itself
2. That pillar data results in expected output on a machine
3. That duplicated or independent known data exists on the machine in the expected state

The #3 option is how I've witnessed most inspect tests, but why not do both? If you want to be paranoid and double check the map.jinja process or pillars, you could have the #1 or #2 tests, and a static dictionary of validation data feed into your CI tests. 

Additionally, these are formulas intended for use by the community. As such, including saltcheck tests which can be run by the end-users (like #1 or #2 above) give further confidence in their robustness and that the pillar docs all actually functioned. I think that even if you didn't use saltcheck as the primary CI validation tool, that it still makes sense to ship saltcheck tests so that functionality and validation can be testing can be leveraged by users.

I do understand the reluctance to use a tool to test itself, but you also want to draw a line around what is being tested. Should `pillar.get` be broken, it is not the job of the saltstack-formulas/foo CI process to catch this, but instead the unit tests around the pillar module itself. The saltstack-formulas tests should be able to rely on a functioning salt system and validate the logic of the formulas themselves and focus on excellent coverage of the data and features exposed.

**Comment by myii** [comment]
And another, required (final) commit.  It also contains a couple of examples of how `saltcheck` and InSpec share similarities.

Package:

```sls
        *InSpec*        |                   *Saltcheck*
------------------------+-------------------------------------------------
package_name =          | {%- set package_name = 'cronie' %}
  case os[:family]      |
  when 'debian'         | {%- if grains.os_family in ['Debian'] %}
    'cron'              | {%-   set package_name = 'cron' %}
  else                  |
    'cronie'            |
  end                   | {%- endif %}
```

Service:

```sls
        *InSpec*        |                   *Saltcheck*
------------------------+-------------------------------------------------
service_name =          | {%- set service_name = 'crond' %}
  case os[:family]      |
  when 'debian', 'suse' | {%- if grains.os_family in ['Debian', 'Suse'] %}
    'cron'              | {%-   set service_name = 'cron' %}
  when 'linux'          |
    case os[:name]      |
    when 'arch'         | {%- elif grains.os_family in ['Arch'] %}
      'cronie'          | {%-   set service_name = 'cronie' %}
    else                |
      'crond'           |
    end                 |
  else                  |
    'crond'             |
  end                   | {%- endif %}
```

* Arguably, `saltcheck` is simpler to work with in this example.

**Comment by myii** [comment]
@mchugh19 Referring back to an earlier comment here: https://github.com/saltstack-formulas/cron-formula/pull/4#issuecomment-541955737.

> ... it looks like it stops searching for paths when it finds the first one, that's why the rest of the tests aren't found.

Due the 1:1 relationship between state file and test file, it would be preferable to have the tests within each sub-directory instead.  Had a look at the code and got to the bottom of this.

Note: All of the below was when testing with:

```
$ ... saltcheck.run_state_tests cron check_all=True
```

---

#### Looking at paths being evaluated with no `saltcheck-tests` directory present

```sls
state_name: cron.package.install
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.service.running
looking in %s to cache tests salt://cron/service/running/saltcheck-tests
looking in %s to cache tests salt://cron/service/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
```

It's checking `cron.config.file` numerous times unnecessarily.  Had to move `processed_states.append(state_name)` into the `if` higher up:

```python
                if state_name in processed_states:
                    copy_states = False
                else:
                    processed_states.append(state_name)
```

Resulting in:

```sls
state_name: cron.package.install
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.service.running
looking in %s to cache tests salt://cron/service/running/saltcheck-tests
looking in %s to cache tests salt://cron/service/saltcheck-tests
```

---

#### Gathering all of the tests (not just the first directory found)

Enabled the tests directory under `cron.package.install` only, resulting in:

```sls
state_name: cron.package.install
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests
BREAK
```

* It's stop looking beyond that point.

Resolved by disabling the `break` statements:

```sls
state_name: cron.package.install
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests  
BREAK (disabled)
Adding .tst file: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/package/saltcheck-tests/install.tst
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
looking in %s to cache tests salt://cron/saltcheck-tests
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.service.running
looking in %s to cache tests salt://cron/service/running/saltcheck-tests
looking in %s to cache tests salt://cron/service/saltcheck-tests
```

* So now it continues to scan the rest of the directories for tests, as it's supposed to.

Enabled the tests directories under `cron.config.file` and `cron.service.running` and now working as required:

```sls
state_name: cron.package.install
looking in %s to cache tests salt://cron/package/install/saltcheck-tests
looking in %s to cache tests salt://cron/package/saltcheck-tests
BREAK (disabled)
Adding .tst file: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/package/saltcheck-tests/install.tst
state_name: cron.config.file
looking in %s to cache tests salt://cron/config/file/saltcheck-tests
looking in %s to cache tests salt://cron/config/saltcheck-tests
BREAK (disabled)
Adding .tst file: %s /tmp/kitchen/var/cache/salt/minion/files/base/cron/config/saltcheck-tests/file.tst
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.config.file
state_name: cron.service.running
looking in %s to cache tests salt://cron/service/running/saltcheck-tests
looking in %s to cache tests salt://cron/service/saltcheck-tests  
BREAK (disabled)

...

      ----------
      TEST RESULTS:
          ----------
          Execution Time:
              3.5308
          Failed:
              0
          Missing Tests:
              0
          Passed:
              25
          Skipped:
              0
```

---

#### Adapted in this formula

I've added another commit here to use this improved structure.  That includes renaming the `.tst` files to match the name of the relevant `.sls` files, to clearly show the 1:1 relationship.  While not critical in this small formula, this implementation is an exemplar for other formula conversions, where this would be much more significant.  In fact, I'd prefer if we avoided the base directory of `salt://<formula>/package/saltcheck-tests` entirely.  So I've gone back to using the version of `saltcheck.py` from `neon`, with these minor adjustments made.

**Comment by myii** [comment]
For clarity, `.tst` files have been renamed and relocated according to their relevant (1:1) `.sls` files:

`.sls` file | `.tst` file
---|---
`.../cron/package/install.sls` | `.../cron/package/saltcheck-tests/install.tst`
`.../cron/config/file.sls` | `.../cron/config/saltcheck-tests/file.tst`
`.../cron/service/running.sls` | `.../cron/service/saltcheck-tests/running.tst`

* This structure will be far more appropriate if used for formulas with numerous state files under each directory.
* It also gives a clearer indication of test coverage; at a glance, it will be easier to determine which state files have tests written for them.

**Comment by mchugh19** [comment]
Good updates @myii! I'm traveling for the next week, but I'll incorporate your solution into the saltcheck patches when I'm back home. Thanks!

**Comment by myii** [comment]
After suggestions from @daks and @aboe76, rearranged all of the test files under a single root-level `saltcheck-tests` directory, as follows:

`.sls` file | `.tst` file
---|---
`.../cron/package/install.sls` | `.../cron/saltcheck-tests/package/install.tst`
`.../cron/config/file.sls` | `.../cron/saltcheck-tests/config/file.tst`
`.../cron/service/running.sls` | `.../cron/saltcheck-tests/service/running.tst`

> ... So I've gone back to using the version of `saltcheck.py` from `neon`, with these minor adjustments made.

With this change, I've readjusted again to base the `saltcheck.py` being used on https://github.com/saltstack-formulas/cron-formula/pull/4#issuecomment-541946848.

**Comment by aboe76** [comment]
@myii wow, that's quick.

**Comment by myii** [comment]
Our first `saltcheck`-enabled formula is now active!  Thanks for getting this started, @mchugh19.

**Pull request merged**
