### PR TITLE
feat(cron.env): add env option in cron-formula

### PR DESCRIPTION
**Pull request by SynPrime**
Add the opportunity to add a ENV-variable in cron forumla.

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by aboe76** [comment]
Updated the PR title, see https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst

**Comment by aboe76** [comment]
@SynPrime nice work, would you mind adding a test for this to the https://github.com/saltstack-formulas/cron-formula/blob/master/test/salt/pillar/cron.sls

**Comment by myii** [comment]
@SynPrime Please have a look at the lint issues:

* https://travis-ci.com/saltstack-formulas/cron-formula/jobs/251741313#L289-L296
* https://travis-ci.com/saltstack-formulas/cron-formula/jobs/251741313#L345-L352

It's useful to have `yamllint` available locally, so that you don't have to rely on the Travis lint stage to work out if everything is OK.

If you need any info about this or the InSpec testing, please don't hesitate to ask here or in Slack.

**Comment by myii** [comment]
@SynPrime Note that we also have `saltcheck` enabled on this repo, which can be used if InSpec tests aren't as easy to provide.  I've already written a test for this PR, so if you can amend your commit message (so it passes the lint), I can add a commit to this PR so that it has a test as well.

**Comment by myii** [comment]
@SynPrime An example of the tests running (2 present and 1 absent):

* https://travis-ci.org/myii/cron-formula/jobs/606697263#L1948-L2017

That's based on the test pillar of:

```yaml
  env:
    env1:
      type: present
      name: PATH
      value: /usr/local/bin:/usr/bin:/bin:/usr/games
      user: root
    env2:
      type: present
      name: MAILTO
      value: example@example.com
      user: root
    env3:
      type: absent
      name: LANG
      value: en_GB.UTF-8
      user: root
```

**Comment by SynPrime** [comment]
Hey @aboe76 @myii,

sorry, this is my first PR in a salt formula. Do you have a documentation for `saltcheck`?

**Comment by myii** [comment]
@SynPrime No problem, welcome and thanks for the contribution.

* https://github.com/saltstack-formulas/template-formula/issues/87
  - This is a good overview
* https://github.com/saltstack-formulas/cron-formula/pull/4
  - This is the long PR that led to the `saltcheck` tests that are in this repo
  - All of the `saltcheck` test files are in this PR, so you can compare the test file with the state file
* https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.saltcheck.html
  - This is the actual module reference but the documentation here isn't up to date with the very latest version of `saltcheck` that we're using

If you have any queries, feel free to ask here (or on Slack).

**Comment by myii** [comment]
@SynPrime You don't need to close the PR each time you want to amend the commits.  Just make the changes and push them, the PR will be updated as well.  To minimise issues in your fork, it's best to avoid using the `master` branch for PRs.  Use a [topic branch](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) instead.

**Comment by SynPrime** [comment]
@myii Sorry, I pushed with --force to my repo. Can I Re-Open the PR?

**Comment by myii** [comment]
@SynPrime No problem, that's why it's best to avoid the `master` branch!  I've still got your commit locally, so what I can do to make this easier is to push your commit and my `saltcheck` commit together in one PR.  Your commit will remain attributed to you.  We can continue the discussion there.  Are you OK with that?

**Comment by myii** [comment]
@SynPrime Since you've reopened this, let's continue here!

**Comment by SynPrime** [comment]
Okay :-)

**Comment by myii** [comment]
Thanks for the contribution, @SynPrime!  It's been merged.  I'll push another PR to add the `saltcheck` test for it.

**Comment by aboe76** [comment]
@SynPrime nice, thank you, hopefully we see more of those!

**Pull request merged**
