### PR TITLE
fix(iteritems): replace with `items` instead (and other fixes for consistency)

### PR DESCRIPTION
**Pull request by myii**
* fix(iteritems): replace with `items` instead
* style(whitespace): base on multiples of `2` rather than `4`
* style(jinja): use Jinja whitespace control

---

The first commit is required, the rest are based on improving the consistency of this formula, with reference to the general standards used for other formulas.

### CODE REVIEW

**Comment by myii** [comment]
* fix(pillar): add job for `task4`

---

This commit is required as well, so that `pillar.example` runs as-is.  Without this, get the error:

```salt
    Data failed to compile:
----------
    Rendering SLS 'base:cron.config' failed: Jinja variable 'dict object' has no attribute 'name'
```

**Comment by myii** [comment]
* fix(quotes): remove single quotes causing issues (or unnecessary)

---

This commit is also necessary otherwise commands (or comments) requiring single quotes cannot be used, such as:

* `/usr/bin/salt '*' test.ping >/root/salt_test_ping`

Also removed the unnecessary quotes from `pillar.example`, in order to make it easier to determine where quotes are absolutely necessary.

**Comment by myii** [comment]
Thanks for the review @aboe76.

**Comment by aboe76** [comment]
@myii shall I merge this?

**Comment by myii** [comment]
@aboe76 I was waiting for a review from @dseira but it has been some time now. Please merge it; we can deal with any issues in a subsequent PR.

**Comment by aboe76** [comment]
@myii merged it.

**Comment by myii** [comment]
Thanks, @aboe76.

**Pull request merged**
